# Application bindings
$terminal = uwsm app -- ghostty
$browser = uwsm app -- chromium --new-window --ozone-platform=wayland
$webapp = $browser --app

bindd = SUPER, RETURN, Terminal, exec, $terminal
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT, M, Music, exec, uwsm app -- spotify
bindd = SUPER SHIFT, N, Neovim, exec, $terminal -e nvim
bindd = SUPER SHIFT, T, Activity, exec, $terminal -e btop
bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, G, Signal, exec, uwsm app -- signal-desktop
bindd = SUPER SHIFT, O, Obsidian, exec, uwsm app -- obsidian -disable-gpu
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- 1password

bindd = SUPER SHIFT, A, ChatGPT, exec, $webapp="https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, $webapp="https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, $webapp="https://app.hey.com/calendar/weeks/"
bindd = SUPER SHIFT, E, Email, exec, $webapp="https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, $webapp="https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, $webapp="https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, $webapp="https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, X, X, exec, $webapp="https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, $webapp="https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, Space
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu
