# hyprlock.conf
# Ref: https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

general {
    hide_cursor = false
}

animations {
    enabled = true

    animation = fadeIn,          1, 5, linear
    animation = fadeOut,         1, 5, linear
    animation = inputFieldDots,  1, 2, linear
}

background {
    monitor =
    path =
    color = rgba(303446ff)
    blur_passes = 0
    blur_size = 0
    noise = 0.0
    contrast = 1.0
    brightness = 1.0
    vibrancy = 0.0
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 320, 48
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(8caaeeff)
    inner_color = rgba(303446ff)
    font_color = rgb(c6d0f5)
    fade_on_empty = false
    placeholder_text = <span foreground="##a5adce" font_family="Iosevka Term Slab" font_size="12pt">Password</span>
    hide_input = false
    rounding = 6
    check_color = rgba(a6d189ff)
    fail_color = rgba(e78284ff)
    fail_text = <span foreground="##e78284" font_family="Iosevka Term Slab"><b>$FAIL</b></span>
    fail_timeout = 2000
    position = 0, -24
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%I:%M %p' | sed 's/^0//')"
    color = rgb(c6d0f5)
    font_size = 54
    font_family = Iosevka Term Slab
    position = 0, 198
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date '+%A, %d %B %Y'
    color = rgb(a5adce)
    font_size = 16
    font_family = Iosevka Term Slab
    position = 0, 140
    halign = center
    valign = center
}
