return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "css",
        "html",
        "go",
        "svelte",
        "javascript",
        "json",
        "latex",
        "lua",
        "markdown",
        "markdown_inline",
        "norg",
        "python",
        "query",
        "regex",
        "scss",
        "tsx",
        "typescript",
        "typst",
        "vim",
        "vue",
        "yaml",
      },
    },
  },
}
