set -g default-terminal "tmux-256color"

# Change leader to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Use Alt-arrow keys to switch panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable mouse support
set -g mouse on

